name: mercury_client
description: Portable HTTP client (Browser and Native support) with memory cache and support for methods GET, HEAD, POST, PUT, DELETE, PATCH and OPTIONS.

version: 2.1.5
homepage: https://github.com/gmpassos/mercury_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  enum_to_string: ^2.0.1
  swiss_knife: ^3.1.1
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
  stream_channel: ^2.1.0
  async: ^2.7.0
  dependency_validator: ^3.1.0
  coverage: ^1.0.3

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
