name: mercury_client
description: Portable HTTP client (Browser and Native support) with memory cache and support for methods GET, HEAD, POST, PUT, DELETE, PATCH and OPTIONS.

version: 2.2.3
homepage: https://github.com/gmpassos/mercury_client

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  enum_to_string: ^2.0.1
  swiss_knife: ^3.2.2
  collection: ^1.18.0
  charset: ^2.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8
  stream_channel: ^2.1.2
  async: ^2.11.0
  dependency_validator: ^3.2.3
  coverage: ^1.9.2

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
