name: mercury_client
description: Portable HTTP client (Browser and Native support) with memory cache and support for methods GET, HEAD, POST, PUT, DELETE, PATCH and OPTIONS.

version: 2.1.8
homepage: https://github.com/gmpassos/mercury_client

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  enum_to_string: ^2.0.1
  swiss_knife: ^3.1.3
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  stream_channel: ^2.1.1
  async: ^2.10.0
  dependency_validator: ^3.2.2
  coverage: ^1.6.1

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
