name: mercury_client
description: Portable HTTP client (Browser and Native support) with memory cache and support for methods GET, POST, PUT, DELETE, PATCH and OPTIONS.

version: 1.1.19
homepage: https://github.com/gmpassos/mercury_client

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  enum_to_string: ^1.0.14
  swiss_knife: ^2.5.26
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  test_coverage: ^0.4.3
  stream_channel: ^2.0.0
  async: ^2.4.2
