name: mercury_client
description: Portable HTTP client (Browser and Native support) with memory cache and support for methods GET, HEAD, POST, PUT, DELETE, PATCH and OPTIONS.

version: 2.2.5
homepage: https://github.com/gmpassos/mercury_client

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  swiss_knife: ^3.2.3
  collection: ^1.19.0
  charset: ^2.0.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  stream_channel: ^2.1.4
  async: ^2.13.0
  dependency_validator: ^3.2.3
  coverage: ^1.11.1

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
