name: mercury_client
description: A Simple HTTP client (Web and Native support).
version: 1.1.6
homepage: https://github.com/gmpassos/mercury_client

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  enum_to_string: ^1.0.8
  swiss_knife: ^2.4.1
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
