name: mercury_client
description: Portable HTTP client (Browser and Native support) with memory cache and support for methods GET, POST, PUT, DELETE, PATCH and OPTIONS.

version: 2.0.0-nullsafety.2
homepage: https://github.com/gmpassos/mercury_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  enum_to_string: ^2.0.0-nullsafety.1
  swiss_knife: ^3.0.2
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  #test_coverage: ^0.4.3
  stream_channel: ^2.1.0
  async: ^2.5.0

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
