name: mercury_client
description: Portable HTTP client (Browser and Native support) with memory cache and support for methods GET, POST, PUT, DELETE, PATCH and OPTIONS.

version: 1.1.12
homepage: https://github.com/gmpassos/mercury_client

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  enum_to_string: ^1.0.9
  swiss_knife: ^2.5.13
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  test_coverage: ^0.4.3
