name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: APT update
        run: apt-get update
      - name: Install Firefox
        run: apt-get install -y firefox-esr xorg
      - name: Current DIR
        run: pwd && pwd >/tmp/test-dir.txt
      - name: Add user tester
        run: adduser --disabled-password tester
      - name: Clean Project + chown tester
        run: |
          rm -rf .dart_tool .packages pubspec.lock
          chown -R tester:tester .
          ls -al
      - name: Dart version
        run: dart --version
      - name: dart pub get
        run: su -c 'cd $(< /tmp/test-dir.txt) && dart pub get' tester
      - name: dart format
        run: su -c 'cd $(< /tmp/test-dir.txt) && dart format -o none --set-exit-if-changed .' tester
      - name: dart analyze
        run: su -c 'cd $(< /tmp/test-dir.txt) && dart analyze --fatal-infos --fatal-warnings .' tester
      - name: dependency_validator
        run: su -c 'cd $(< /tmp/test-dir.txt) && dart run dependency_validator' tester
      - name: Run VM tests
        run: su -c 'DISPLAY=:0 cd $(< /tmp/test-dir.txt) && dart test -p vm' tester
      - name: Run Browser tests (Firefox)
        run: su -c 'DISPLAY=:0 cd $(< /tmp/test-dir.txt) && dart test -p firefox' tester
      - name: Generate coverage report
        run: |
          su -c 'DISPLAY=:0 cd $(< /tmp/test-dir.txt) && dart test --coverage=./coverage -p vm,firefox' tester
          su -c 'DISPLAY=:0 cd $(< /tmp/test-dir.txt) && dart pub global run coverage:format_coverage --packages=.packages --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage' tester
          su -c 'DISPLAY=:0 cd $(< /tmp/test-dir.txt) && chmod -R 777 ./coverage' tester
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
          flags: unittests
          env_vars: OS,DART
          fail_ci_if_error: true
          verbose: true
      - name: publish --dry-run
        run: su -c 'DISPLAY=:0 cd $(< /tmp/test-dir.txt) && dart pub publish --dry-run' tester
